---
title: "Milestone 2"
author: "Amanda Su"
date: "9/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chicago Ride Share Comparisons. Does Christmas affect ride-share and rider behavior?

By Albert Shin, [Project Link](https://treblashin.shinyapps.io/chicago-rides/)

Albert looked at how Christmas (a holiday) affected ride-share and rider behavior in 2018. The original dataset contained over 17 million rows of data, so Albert decided to only look at an compare data from December 25, 2018 (a holiday) and December 4, 2018 (a non-holiday that is the same day of the week as December 25). He was still left with 300 thousand rows so he took a random sample of 25 thousand rows to ensure graphs were still readable. 

I thought his project was absolutely amazing. First of all, it was so cool how he plotted his data points on an actual map where you could use a slider to see the number of rides per day and zoom in to get a closer look at the exact geographical locations of data points — which is so much more interesting and informative than just a simple x-y axis graph. In addition to the map, Albert also included a bar graph clearly showing the exact numerical difference between the number of rideshares on a non-holiday day and that of a holiday day. His line graph lets you see the change in number of rides throughout the day, which highlighted that on December 4 there were peaks during the hours people get on and off work while those peaks were nonexistent in Christmas line. This meant he could reasonably guess that it's because people call rides to and from work on workdays. The variety of graphs and information (tips, fare, miles, additional charges) made this project very professional and thorough. 

The only criticism I have, which Albert addressed himself, is the lack of demographic information (gender, age, race/ethnicity). If he had this information, we could have potentially looked for interesting patterns in the data. For example, an age variable could have corroborated Albert's guess that the peaks in the December 4 data were because of working hours by comparing the number of rides across age groups (students, working adults, retired people). 

## What makes a top hit on the Billboard charts?

By Jordan Topoleski, [Project Link](https://jtopoleski.shinyapps.io/What-Makes-a-Hit-Song/)

The question Jordan explored was what are the possible contributing factors to making a Billboard charts top hit. He looked at data from the past some 20 years, starting in 2000. What was really great about Jordan's project was on his line graph showing the number of songs on the Billboard charts over the years, he included vertical lines indicating the inception of Youtube, Spotify, and Apple Music. I thought this provided some really important and useful context for understanding the data and how the changing music industry might have played a role in shaping the criteria for what makes a Billboardcharts top hit. He also added additional variables to his bar chart relating song genre and number of Billboard appearances, which made it a lot more informational because you could compare across those variables to check for any patterns. The variables were the year (you can check boxes for one, multiple, or all years to see a specific or cumulative value) and the song's highest rating. 

One downside to Jordan's project was while he could highlight correlation between variables, he could not determine a causal relationship between any of the variables and whether not the songs were top hits because there was no randomized experiment. Also, I think something that Jordan could have looked into more was the "artist" variable. I'm guessing that perhaps a lot of artists who are already really famous are more likely to get more support and listeners because of their fanbase and, as a result, consecutive Billboard top hits. It would have been interesting for him to look at whether or not already having made a Billboard top hit had any kind of correlation with the success of making future ones. 



